using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;
using System.Globalization;

namespace StoredProcedureMigrationPrototype.Shared.Migrations.deprecated
{
    public static class DatabaseMigrationProcessorOld
    {
        /// <summary>
        /// Automatically generates a migration if there are model changes and applies it to the database.
        /// </summary>
        /// <typeparam name="TContext">The DbContext type to generate the migration for.</typeparam>
        /// <param name="serviceProvider">The service provider.</param>
        /// <param name="migrationsPath">The path where migration files should be saved.</param>
        public static void GenerateAndApplyMigrationIfPending<TContext>(IServiceProvider serviceProvider, string migrationsPath)
            where TContext : DbContext
        {
            using var scope = serviceProvider.CreateScope();
            var dbContext = scope.ServiceProvider.GetRequiredService<TContext>();

            try
            {
                // Check if there are pending model changes
                if (!AreModelChangesDetected(dbContext))
                {
                    Console.WriteLine("No model changes detected. Skipping migration generation.");
                    return;
                }

                Console.WriteLine("Model changes detected. Generating migration...");

                // Generate migration name in the format YYYYMMDD.HHMM
                var timestamp = DateTime.UtcNow.ToString("yyyyMMdd.HHmm", CultureInfo.InvariantCulture);
                var migrationName = $"{timestamp}_AutoGeneratedMigration";

                // Ensure the migrations directory exists
                if (!Directory.Exists(migrationsPath))
                {
                    Directory.CreateDirectory(migrationsPath);
                }

                // Generate the migration
                var migrationScript = GenerateMigrationScript<TContext>(dbContext, migrationName, migrationsPath);

                if (string.IsNullOrWhiteSpace(migrationScript))
                {
                    Console.WriteLine("No migration script generated. Skipping database update.");
                    return;
                }

                Console.WriteLine($"Migration script generated: {migrationName}.sql");

                // Apply the migration to the database
                Console.WriteLine("Applying migration to the database...");
                dbContext.Database.Migrate();
                Console.WriteLine("Migration applied successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error generating or applying migration: {ex.Message}");
            }
        }

        /// <summary>
        /// Checks whether there are any model changes that require a new migration.
        /// </summary>
        private static bool AreModelChangesDetected(DbContext dbContext)
        {
            // Get the model differ service
            var modelDiffer = dbContext.GetService<IMigrationsModelDiffer>();

            // Get the current relational model
            var currentModel = dbContext.Model.GetRelationalModel();

            // Get the last snapshot relational model
            var lastModel = dbContext.GetService<IMigrationsAssembly>().ModelSnapshot?.Model.GetRelationalModel();

            // If there is no snapshot (lastModel is null), assume model changes exist
            if (lastModel == null)
            {
                Console.WriteLine("No snapshot found. Assuming model changes exist.");
                return true;
            }

            // Compare the current model with the last applied snapshot
            return modelDiffer.HasDifferences(lastModel, currentModel);
        }


        /// <summary>
        /// Generates a SQL migration script and saves it to the specified path.
        /// </summary>
        private static string GenerateMigrationScript<TContext>(DbContext dbContext, string migrationName, string migrationsPath)
            where TContext : DbContext
        {
            try
            {
                // Add migration metadata to the database
                var migrationAssembly = dbContext.GetService<IMigrationsAssembly>();
                var migrationId = $"{migrationName.Replace('.', '_')}";
                var sqlScript = dbContext.Database.GenerateCreateScript();

                // Save migration SQL script to file
                var migrationFilePath = Path.Combine(migrationsPath, $"{migrationName}.sql");
                File.WriteAllText(migrationFilePath, sqlScript);

                return sqlScript;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error generating migration script: {ex.Message}");
                return null;
            }
        }
    }
}
